services:
  frontend:
    build: ./frontend
    container_name: tienda-frontend
    ports:
      - "8080:80"
    depends_on:
      - backend
    networks:
      - tienda-net

  backend:
    build: ./backend
    container_name: tienda-backend
    environment:
      DB_HOST: db
      DB_USER: root
      DB_PASSWORD: admin123
      DB_NAME: tienda_perritos
      DB_PORT: 3306
    ports:
      - "3001:3001"
    depends_on:
      - db
    networks:
      - tienda-net

  db:
    image: mysql:8
    container_name: tienda-db
    environment:
      MYSQL_ROOT_PASSWORD: admin123
      MYSQL_DATABASE: tienda_perritos
    volumes:
      - dbdata:/var/lib/mysql
      - ./db/init.sql:/docker-entrypoint-initdb.d/init.sql
    networks:
      - tienda-net

volumes:
  dbdata:

networks:
  tienda-net:
    driver: bridge