name: CI/CD Tienda Perritos

on:
  push:
    branches:
      - deploy

env:
  AWS_REGION: us-east-1
  ECS_CLUSTER: tienda-cluster
  FRONTEND_SERVICE: tienda-frontend-service
  BACKEND_SERVICE: tienda-backend-service

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout código
        uses: actions/checkout@v4

      - name: Configurar credenciales AWS
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-session-token: ${{ secrets.AWS_SESSION_TOKEN }}
          aws-region: ${{ env.AWS_REGION }}

      - name: Debug AWS ECS
        run: |
          echo "Cuenta AWS usada por GitHub Actions:"
          aws sts get-caller-identity

          echo "Clusters disponibles:"
          aws ecs list-clusters --region $AWS_REGION

          echo "Servicios dentro de tienda-cluster:"
          aws ecs list-services \
            --cluster $ECS_CLUSTER \
            --region $AWS_REGION

          echo "Detalle backend:"
          aws ecs describe-services \
            --cluster $ECS_CLUSTER \
            --services $BACKEND_SERVICE \
            --region $AWS_REGION

          echo "Detalle frontend:"
          aws ecs describe-services \
            --cluster $ECS_CLUSTER \
            --services $FRONTEND_SERVICE \
            --region $AWS_REGION

      - name: Login a Amazon ECR
        uses: aws-actions/amazon-ecr-login@v2

      - name: Build y push imagen Frontend
        run: |
          docker build -t tienda-frontend ./frontend
          docker tag tienda-frontend:latest ${{ secrets.AWS_ACCOUNT_ID }}.dkr.ecr.us-east-1.amazonaws.com/tienda-frontend:latest
          docker push ${{ secrets.AWS_ACCOUNT_ID }}.dkr.ecr.us-east-1.amazonaws.com/tienda-frontend:latest

      - name: Build y push imagen Backend
        run: |
          docker build -t tienda-backend ./backend
          docker tag tienda-backend:latest ${{ secrets.AWS_ACCOUNT_ID }}.dkr.ecr.us-east-1.amazonaws.com/tienda-backend:latest
          docker push ${{ secrets.AWS_ACCOUNT_ID }}.dkr.ecr.us-east-1.amazonaws.com/tienda-backend:latest

      - name: Deploy Frontend a ECS
        run: |
          aws ecs update-service \
            --cluster $ECS_CLUSTER \
            --service $FRONTEND_SERVICE \
            --force-new-deployment \
            --region $AWS_REGION

      - name: Deploy Backend a ECS
        run: |
          aws ecs update-service \
            --cluster $ECS_CLUSTER \
            --service $BACKEND_SERVICE \
            --force-new-deployment \
            --region $AWS_REGION